### PR TITLE
[walletConnect v2.2.0-alpha.1]: Fix - walletConnect support for wallet_switchEthereumChain method

### LINKED ISSUE #1313: [Feature]: Add support for wallet_switchEthereumChain in the walletConnect provider
### Is your request related to a problem?

- When a user connects to our app with walletconnect we want to be able to switch the chain they are connected to in our app. 

### Feature Description

Implement wallet_switchEthereumChain in the below provider. My guess is that the wallet connect session could be updated to the passed in chainId. 

- https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/walletconnect/src/index.ts#L183

### Alternative Solutions

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Adamj1232**
### Description
- Adds support for walletconnect `wallet_switchEthereumChain`
- Handle chain ID returned as hex in some situations
- Closes #1313 & PR: #1351 

Before Fix: https://www.loom.com/share/25801628496448b6962c861d9178b5dd

After Fix: https://www.loom.com/share/c6f71389b0c7463ca582bb9b9ec348ce

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [x] I have run `yarn check` & `yarn build` to confirm there are not any associated errors
- [x] This PR passes the Circle CI checks

### CODE REVIEW

File: packages/walletconnect/src/index.ts [hunk 1]
```diff
@@ -15,6 +15,14 @@ interface WalletConnectOptions {
   connectFirstChainId?: boolean
 }
 
+const isHexString = (value: string | number) => {
```
Comment (Adamj1232) [inline packages/walletconnect/src/index.ts:18]: Same method used by ethers project utils package but didn't want to pull in the whole package as a dep.

**Review by aaronbarnardsound — APPROVED** [review]
Nice!

**Comment by CryptoKira** [comment]
merge it, just do it
